In [32]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
sys.path.append(str(PROJECT_ROOT))

import pandas as pd

from src.data.load_data import DataLoader
from src.data.preprocess import DataPreprocessor
from src.data.feature_engineering import FeatureEngineer

In [33]:
file_path = (
    PROJECT_ROOT
    / "data"
    / "raw"
    / "jan to may police violation_anonymized791b166.csv"
)

loader = DataLoader(file_path)

df = loader.load()
df = loader.remove_duplicates(df)
df = loader.parse_datetime(df)

DataPreprocessor.validate_schema(df)

df = DataPreprocessor.remove_invalid_coordinates(df)

df = FeatureEngineer.add_temporal_features(df)
df = FeatureEngineer.parse_violation_types(df)

print(df.shape)
df.head()

2026-06-16 22:48:31.899 | INFO     | src.data.load_data:load:15 - Loading dataset from /Users/meharkapoor7/ParkSense-AI/data/raw/jan to may police violation_anonymized791b166.csv
2026-06-16 22:48:32.712 | INFO     | src.data.load_data:load:27 - Loaded dataset with shape (298450, 24)
2026-06-16 22:48:32.941 | INFO     | src.data.load_data:remove_duplicates:44 - Removed 0 duplicates.

(298450, 29)

,id,latitude,longitude,location,vehicle_number,vehicle_type,description,violation_type,offence_code,created_datetime,...,data_sent_to_scita_timestamp,updated_vehicle_number,updated_vehicle_type,validation_status,validation_timestamp,hour,day,month,weekday,is_weekend
0,FKID000000,12.925557,77.618665,"18th Main Road, Block 2, Koramangala, Bengalur...",FKN00GL0000,CAR,NaN,"[WRONG PARKING, PARKING NEAR ROAD CROSSING]","[112,104]",2023-11-20 00:28:46+00:00,...,NaN,FKN00GL0000,MAXI-CAB,approved,2023-11-30 03:08:24.818+00,0.0,20.0,11.0,Monday,0
1,FKID000001,12.905463,77.700778,"Sarjapura Main Road, The Grove, Janatha Colony...",FKN00GL0001,CAR,NaN,[NO PARKING],[113],2023-11-24 22:46:46+00:00,...,NaN,NaN,NaN,NaN,NaN,22.0,24.0,11.0,Friday,0
2,FKID000002,12.925449,77.618504,"Koramangala 2nd Block, Kormangala West, Bengal...",FKN00GL0002,CAR,NaN,"[WRONG PARKING, PARKING IN A MAIN ROAD]","[112,107]",2023-11-20 00:27:46+00:00,...,NaN,FKN00GL0002,MAXI-CAB,approved,2023-11-30 03:08:56.998+00,0.0,20.0,11.0,Monday,0
3,FKID000003,12.956521,77.518618,"6th Cross Road, Manasa Layout, Nagarbhavi, Ben...",FKN00GL0003,SCOOTER,NaN,[NO PARKING],[113],2023-11-16 06:47:46+00:00,...,NaN,FKN00GL0003,SCOOTER,approved,2023-11-18 23:35:12.428+00,6.0,16.0,11.0,Thursday,0
4,FKID000004,12.977767,77.580545,"Kalidasa Road, Gandhinagar, Nehru Nagar, Benga...",FKN00GL0004,TANKER,NaN,[NO PARKING],[113],2023-11-22 04:56:46+00:00,...,NaN,FKN00GL0004,TANKER,approved,2023-11-30 03:11:32.796+00,4.0,22.0,11.0,Wednesday,0

In [34]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 298450 entries, 0 to 298449
Data columns (total 29 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   id                            298450 non-null  str
 1   latitude                      298450 non-null  float64
 2   longitude                     298450 non-null  float64
 3   location                      295409 non-null  str
 4   vehicle_number                298450 non-null  str
 5   vehicle_type                  298450 non-null  str
 6   description                   0 non-null       float64
 7   violation_type                298450 non-null  object
 8   offence_code                  298450 non-null  str
 9   created_datetime              298445 non-null  datetime64[us, UTC]
 10  closed_datetime               0 non-null       float64
 11  modified_datetime             298450 non-null  str
 12  device_id                     298450 non-null  str
 13  created_by_id                 298445 non-null  str
 14  center_code                   287190 non-null  float64
 15  police_station                298445 non-null  str
 16  data_sent_to_scita            298450 non-null  bool
 17  junction_name                 298445 non-null  str
 18  action_taken_timestamp        0 non-null       float64
 19  data_sent_to_scita_timestamp  42161 non-null   str
 20  updated_vehicle_number        173196 non-null  str
 21  updated_vehicle_type          173196 non-null  str
 22  validation_status             173196 non-null  str
 23  validation_timestamp          173196 non-null  str
 24  hour                          298445 non-null  float64
 25  day                           298445 non-null  float64
 26  month                         298445 non-null  float64
 27  weekday                       298445 non-null  str
 28  is_weekend                    298450 non-null  int64
dtypes: bool(1), datetime64[us, UTC](1), float64(9), int64(1), object(1), str(16)
memory usage: 64.0+ MB

In [35]:
df.describe(include="all").T

,count,unique,top,freq,mean,min,25%,50%,75%,max,std
id,298450,298450,FKID000000,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
latitude,298450.0,NaN,NaN,NaN,12.980802,12.802667,12.963331,12.977284,12.997467,13.293684,0.049732
longitude,298450.0,NaN,NaN,NaN,77.600512,77.442553,77.571198,77.584114,77.621529,77.771735,0.050518
location,295409,10942,"Unnamed Road, Begur Chikkanahalli, Bengaluru, ...",4090,NaN,NaN,NaN,NaN,NaN,NaN,NaN
vehicle_number,298450,231890,FKN00GL4424,55,NaN,NaN,NaN,NaN,NaN,NaN,NaN
vehicle_type,298450,22,SCOOTER,94856,NaN,NaN,NaN,NaN,NaN,NaN,NaN
description,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
violation_type,298450,991,[WRONG PARKING],138764,NaN,NaN,NaN,NaN,NaN,NaN,NaN
offence_code,298450,991,[112],138764,NaN,NaN,NaN,NaN,NaN,NaN,NaN
created_datetime,298445,NaN,NaN,NaN,2024-01-21 20:00:41.543500+00:00,2023-11-09 19:11:46+00:00,2023-12-16 01:43:46+00:00,2024-01-19 04:52:46+00:00,2024-02-27 08:50:46+00:00,2024-04-08 17:30:46+00:00,NaN
closed_datetime,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
modified_datetime,298450,298450,2023-11-28 04:48:04.582978+00,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
device_id,298450,3070,FKDEV00021,4344,NaN,NaN,NaN,NaN,NaN,NaN,NaN
created_by_id,298445,2666,FKUSR00021,4099,NaN,NaN,NaN,NaN,NaN,NaN,NaN
center_code,287190.0,NaN,NaN,NaN,23.023013,2.0,11.0,17.0,29.0,88.0,20.006118
police_station,298445,54,Upparpet,34468,NaN,NaN,NaN,NaN,NaN,NaN,NaN
data_sent_to_scita,298450,2,True,255893,NaN,NaN,NaN,NaN,NaN,NaN,NaN
junction_name,298445,169,No Junction,147880,NaN,NaN,NaN,NaN,NaN,NaN,NaN
action_taken_timestamp,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
data_sent_to_scita_timestamp,42161,42161,2024-04-01 17:45:48.438875+00,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
updated_vehicle_number,173196,143133,FKN00GL17863,36,NaN,NaN,NaN,NaN,NaN,NaN,NaN
updated_vehicle_type,173196,22,SCOOTER,54867,NaN,NaN,NaN,NaN,NaN,NaN,NaN
validation_status,173196,5,approved,115400,NaN,NaN,NaN,NaN,NaN,NaN,NaN
validation_timestamp,173196,170115,2024-01-08 06:10:01.503+00,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
hour,298445.0,NaN,NaN,NaN,9.20319,0.0,3.0,5.0,20.0,23.0,8.287866
day,298445.0,NaN,NaN,NaN,15.669349,1.0,8.0,16.0,23.0,31.0,8.730863
month,298445.0,NaN,NaN,NaN,5.525517,1.0,2.0,3.0,11.0,12.0,4.631114
weekday,298445,7,Sunday,46863,NaN,NaN,NaN,NaN,NaN,NaN,NaN
is_weekend,298450.0,NaN,NaN,NaN,0.30253,0.0,0.0,0.0,1.0,1.0,0.459354

In [36]:
df.columns.tolist()

['id',
 'latitude',
 'longitude',
 'location',
 'vehicle_number',
 'vehicle_type',
 'description',
 'violation_type',
 'offence_code',
 'created_datetime',
 'closed_datetime',
 'modified_datetime',
 'device_id',
 'created_by_id',
 'center_code',
 'police_station',
 'data_sent_to_scita',
 'junction_name',
 'action_taken_timestamp',
 'data_sent_to_scita_timestamp',
 'updated_vehicle_number',
 'updated_vehicle_type',
 'validation_status',
 'validation_timestamp',
 'hour',
 'day',
 'month',
 'weekday',
 'is_weekend']

In [37]:
from collections import Counter

counter = Counter()

for violations in df["violation_type"]:
    counter.update(violations)

counter.most_common(20)

[('WRONG PARKING', 164977),
 ('NO PARKING', 139050),
 ('PARKING IN A MAIN ROAD', 23943),
 ('DEFECTIVE NUMBER PLATE', 7848),
 ('PARKING ON FOOTPATH', 3757),
 ('PARKING NEAR BUSTOP/SCHOOL/HOSPITAL ETC', 2403),
 ('DOUBLE PARKING', 2037),
 ('PARKING NEAR ROAD CROSSING', 1687),
 ('REFUSE TO GO FOR HIRE', 887),
 ('PARKING NEAR TRAFFIC LIGHT OR ZEBRA CROSS', 525),
 ('PARKING OPPOSITE TO ANOTHER PARKED VEHICLE', 486),
 ('USING BLACK FILM/OTHER MATERIALS', 248),
 ('PARKING OTHER THAN BUS STOP', 242),
 ('DEMANDING EXCESS FARE', 240),
 ('WITHOUT SIDE MIRROR', 47),
 ('H T V PROHIBITED', 31),
 ('OBSTRUCTING DRIVER', 16),
 ('AGAINST ONE WAY/NO ENTRY', 9),
 ('FAIL TO USE SAFETY BELTS', 8),
 ('VIOLATING LANE DISIPLINE', 5)]

In [38]:
df[["latitude", "longitude"]].describe()

            latitude      longitude
count  298450.000000  298450.000000
mean       12.980802      77.600512
std         0.049732       0.050518
min        12.802667      77.442553
25%        12.963331      77.571198
50%        12.977284      77.584114
75%        12.997467      77.621529
max        13.293684      77.771735

In [39]:
df["location"].nunique()

10942

In [40]:
df["location"].value_counts().head(20)

location
Unnamed Road, Begur Chikkanahalli, Bengaluru, Karnataka. Pin-562149 (India)                                                4090
Kamaraj Road, Sri Nagamma Devi Circle, Sivanchetti Gardens, Bengaluru, Karnataka. Pin-560042 (India)                       3999
New Horizon College Road, New Horizon College of Engineering, Kadubisanahalli, Bengaluru, Karnataka. Pin-560103 (India)    3785
MBT Road, Devasandra Junction, KR Puram, Bengaluru, Karnataka. Pin-560036 (India)                                          3027
Dispensary Road, Tasker Town, Shivaji Nagar, Bengaluru, Karnataka. Pin-560001 (India)                                      2670
Bellary Road, Vinayaka Nagar, Hebbal, Bengaluru, Karnataka. Pin-560024 (India)                                             2639
5th Main Road, Kempe Gowda Circle, Gandhi Nagar, Bengaluru, Karnataka. Pin-560009 (India)                                  2604
Main Guard Cross Road, Tasker Town, Shivaji Nagar, Bengaluru, Karnataka. Pin-560001 (India)                                2549
New Horizon College Road, Embassy Tech Village, Devara Beesana Halli, Bengaluru, Karnataka. Pin-560103 (India)             2416
3rd Cross Road, Kempegowda Extension, Chickpete, Bengaluru, Karnataka. Pin-560009 (India)                                  2315
Mysore Road, Sri Krishna Rajendra Market, Chickpete, Bengaluru, Karnataka. Pin-560002 (India)                              2122
80 Feet Ring Road, Orion, Brigade Gateway, Malleshwaram West, Bengaluru, Karnataka. Pin-560055 (India)                     2117
Meenakshi Koil Street, Shivaji Nagar, Bengaluru, Karnataka. Pin-560001 (India)                                             2111
Subedar Chatram Road, RK Puram, Gandhi Nagar, Bengaluru, Karnataka. Pin-560009 (India)                                     1940
Dickenson Road, Sri Nagamma Devi Circle, Sivanchetti Gardens, Bengaluru, Karnataka. Pin-560042 (India)                     1924
Chord Road, Manuvana, Vijaya Nagar, Bengaluru, Karnataka. Pin-560040 (India)                                               1869
Sri Sankasta Hara Ganapati Temple Road, RPC Layout, Vijaya Nagar Stage 2, Bengaluru, Karnataka. Pin-560104 (India)         1857
6th Main Road, RK Puram, Gandhi Nagar, Bengaluru, Karnataka. Pin-560009 (India)                                            1797
Sahakar Nagar Road, Fortuna Acacia, Byatarayanapura, Bengaluru, Karnataka. Pin-560092 (India)                              1743
Pailwan M Krishnappa Road, Shoukath Mohalla, Nagartapete, Bengaluru, Karnataka. Pin-560002 (India)                         1529
Name: count, dtype: int64